"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/ThemeToggle";
import { IconBrain, IconCode, IconRocket, IconUsers } from "@tabler/icons-react";
import { Marquee } from "@/components/magicui/marquee";

const features = [
  {
    icon: <IconBrain className="w-6 h-6" />,
    title: "AI-Powered Questions",
    description: "Get personalized interview questions generated by advanced AI technology",
  },
  {
    icon: <IconCode className="w-6 h-6" />,
    title: "Multiple Courses",
    description: "Practice questions from various technical and non-technical courses",
  },
  {
    icon: <IconRocket className="w-6 h-6" />,
    title: "Real-time Feedback",
    description: "Instant question generation and immediate feedback on your answers",
  },
  {
    icon: <IconUsers className="w-6 h-6" />,
    title: "Community Learning",
    description: "Join a community of learners preparing for their dream jobs",
  },
];

const testimonials = [
  {
    name: "Sarah",
    role: "Software Engineer",
    text: "SEEKHO helped me ace my technical interviews. The AI-generated questions were spot on!",
  },
  {
    name: "Michael",
    role: "Product Manager",
    text: "The variety of courses and real-time feedback made my interview preparation much more effective.",
  },
  {
    name: "Emily",
    role: "Data Scientist",
    text: "I love how SEEKHO adapts to my learning style. The questions are challenging but relevant.",
  },
];

export default function LandingPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-gray-50 to-white dark:from-gray-900 dark:to-gray-800">
      <div className="absolute top-4 right-4">
        <ThemeToggle />
      </div>
      
      <div className="container flex flex-col items-center justify-center min-h-screen px-4 py-16 mx-auto text-center">
        <div className="space-y-8">
          <div className="space-y-4">
            <h1 className="text-6xl font-bold tracking-tight text-gray-900 dark:text-white">
              SEEKHO
            </h1>
            <p className="max-w-2xl mx-auto text-lg text-gray-600 dark:text-gray-400">
              Master your interview skills with AI-powered practice questions. 
              Get personalized questions for your field and improve your chances of success.
            </p>
          </div>

          <div className="flex justify-center gap-4">
            <Link href="/courses">
              <Button 
                size="lg"
                className="bg-gray-900 text-white hover:bg-gray-800 dark:bg-white dark:text-gray-900 dark:hover:bg-gray-100"
              >
                Get Started
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </main>
  );
}
